-- DROP TRIGGER IF EXISTS update_timestamp_trigger ON USERS;
--
-- DROP FUNCTION IF EXISTS update_timestamp();

DROP TABLE REFRESH_TOKENS;

DROP TABLE USERS_ROLES;

DROP TABLE ROLES;

DROP TABLE USERS;